# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - goreleaser build --single-target --snapshot

  build-all:
    cmds:
      - goreleaser build --clean

  release:
    cmds:
      - goreleaser release --clean
